Repository PowerShell/PSDscResources, pull requests merged in 2019-01, with the labels that each got.

#132 Update CommonResourceHelper and ResourceHelper tests to Pester 4 standards
  README.md
  Tests/Unit/CommonResourceHelper.Tests.ps1
  Tests/Unit/ResourceSetHelper.Tests.ps1
Labels: needs review

#113 Add pull request template and issue templates
  .github/ISSUE_TEMPLATE/General.md
  .github/ISSUE_TEMPLATE/Problem_with_resource.md
  .github/ISSUE_TEMPLATE/Resource_proposal.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs review

#133 Update environment tests to meet Pester 4.0.0 standards
  README.md
  Tests/Integration/MSFT_EnvironmentResource.EndToEnd.Tests.ps1
  Tests/Integration/MSFT_EnvironmentResource.Integration.Tests.ps1
  Tests/Integration/MSFT_EnvironmentResource.config.ps1
  Tests/Unit/MSFT_EnvironmentResource.Tests.ps1
Labels: ready for merge

#135 Update Group and GroupSet tests to meet Pester 4 standards
  DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1
  README.md
  Tests/Integration/GroupSet.Integration.Tests.ps1
  Tests/Integration/GroupSet.config.ps1
  Tests/Integration/MSFT_GroupResource.Integration.Tests.ps1
  Tests/Integration/MSFT_GroupResource_Members.config.ps1
  Tests/Integration/MSFT_GroupResource_MembersToIncludeExclude.config.ps1
  Tests/Integration/MSFT_GroupResource_NoMembers.config.ps1
  Tests/Unit/MSFT_GroupResource.Tests.ps1
Labels: waiting for author response
